name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Push Docker iamge
      run: |
        docker tag docker_demo:latest ${{ secrets.DOCKER_USERNAME }}/docker_demo:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/docker_demo:latest

    
